# type: ignore
from backend.routes.login import login

from backend.routes.departments import departments
from backend.routes.departments_create import departments_create
from backend.routes.departments_id import departments_id
from backend.routes.departments_id_delete import departments_id_delete

from backend.routes.departments_id_students_create import departments_id_students_create
from backend.routes.departments_id_students_generate_passwords import departments_id_students_generate_passwords
from backend.routes.departments_id_students_id_delete import departments_id_students_id_delete

from backend.routes.vocabulary_sets import vocabulary_sets
from backend.routes.vocabulary_sets_create import vocabulary_sets_create
from backend.routes.vocabulary_sets_id import vocabulary_sets_id
from backend.routes.vocabulary_sets_id_delete import vocabulary_sets_id_delete

from backend.routes.vocabulary_sets_id_departments_add import vocabulary_sets_id_departments_add
from backend.routes.vocabulary_sets_id_departments_remove import vocabulary_sets_id_departments_remove

from backend.routes.vocabulary_sets_id_words_create import vocabulary_sets_id_words_create
from backend.routes.vocabulary_sets_id_words_id_delete import vocabulary_sets_id_words_id_delete
from backend.routes.vocabulary_sets_id_words_id_update import vocabulary_sets_id_words_id_update
from backend.routes.vocabulary_sets_id_words_id_log import vocabulary_sets_id_words_id_log

from backend.routes.vocabulary_sets_id_statistics import vocabulary_sets_id_statistics
from backend.routes.vocabulary_sets_id_generate_context_sentences import vocabulary_sets_id_generate_context_sentences

from backend.routes.set_prompt_context_sentences import set_prompt_context_sentences
